# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

import os
Import('genv')

inc = [
    genv["PROJECT_ROOT"]+"/Inc",
    genv["STM32_DRIVERS_PATH"] + "/STM32F1xx_HAL_Driver/Inc",
    genv["STM32_DRIVERS_PATH"] + "/STM32F1xx_HAL_Driver/Inc/Legacy",
    genv["STM32_DRIVERS_PATH"] + "/CMSIS/Device/ST/STM32F1xx/Include",
    genv["STM32_DRIVERS_PATH"] + "/CMSIS/Include",
]

env = Environment()

env["CC"] = genv["CC"]
env["CXX"] = genv["CXX"]
env["AS"] = genv["AS"]
env["AR"] = genv["AR"]
env["LINK"] = genv["LINK"]
env["OBJCOPY"] = genv["OBJCOPY"]
env["NM"] = genv["NM"]
env["ENV"] = genv["ENV"]

env["LINKFLAGS"] = genv["LINKFLAGS"]
env["CFLAGS"] = genv["CFLAGS"]
env["ASFLAGS"] = genv["ASFLAGS"]

dst = "STM32F1xx_CMSIS_SYSTEM"
src = [
    "Source/Templates/system_stm32f1xx.c", 
]
lib = []

stm32_hal_driver = env.StaticLibrary(target=dst, source=src, LIBS=lib, CPPPATH=inc)
Return("stm32_hal_driver")
