# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

import os
Import('genv')

inc = [
    'Inc',
    'Inc/Legacy',
    genv["PROJECT_ROOT"]+"/Inc",
    genv["STM32_DRIVERS_PATH"] + "/CMSIS/Device/ST/STM32F1xx/Include",
    genv["STM32_DRIVERS_PATH"] + "/CMSIS/Include",
]

env = Environment()

env["CC"] = genv["CC"]
env["CXX"] = genv["CXX"]
env["AS"] = genv["AS"]
env["AR"] = genv["AR"]
env["LINK"] = genv["LINK"]
env["OBJCOPY"] = genv["OBJCOPY"]
env["NM"] = genv["NM"]
env["ENV"] = genv["ENV"]

env["LINKFLAGS"] = genv["LINKFLAGS"]
env["CFLAGS"] = genv["CFLAGS"]
env["ASFLAGS"] = genv["ASFLAGS"]

dst = "STM32F1XX_HAL"
src = [
    "Src/stm32f1xx_hal_iwdg.c",
    "Src/stm32f1xx_hal_adc.c",
    "Src/stm32f1xx_hal_rcc.c",
    "Src/stm32f1xx_hal_rcc_ex.c",
    "Src/stm32f1xx_hal_dac_ex.c",
    "Src/stm32f1xx_hal_irda.c",
    "Src/stm32f1xx_hal_rtc_ex.c",
    "Src/stm32f1xx_hal_nand.c",
    "Src/stm32f1xx_hal_rtc.c",
    "Src/stm32f1xx_hal_eth.c",
    "Src/stm32f1xx_ll_sdmmc.c",
    "Src/stm32f1xx_hal_wwdg.c",
    "Src/stm32f1xx_hal_pcd.c",
    "Src/stm32f1xx_hal_crc.c",
    "Src/stm32f1xx_hal_flash_ex.c",
    "Src/stm32f1xx_hal_hcd.c",
    "Src/stm32f1xx_hal_dma.c",
    "Src/stm32f1xx_ll_fsmc.c",
    "Src/stm32f1xx_hal_smartcard.c",
    "Src/stm32f1xx_hal_can.c",
    "Src/stm32f1xx_hal_cortex.c",
    "Src/stm32f1xx_hal_uart.c",
    "Src/stm32f1xx_hal_flash.c",
    "Src/stm32f1xx_hal_gpio.c",
    "Src/stm32f1xx_hal_pwr.c",
    "Src/stm32f1xx_hal_tim.c",
    "Src/stm32f1xx_hal_i2s.c",
    "Src/stm32f1xx_hal_spi.c",
    "Src/stm32f1xx_hal_pccard.c",
    "Src/stm32f1xx_hal_dac.c",
    "Src/stm32f1xx_hal_tim_ex.c",
    "Src/stm32f1xx_ll_usb.c",
    "Src/stm32f1xx_hal.c",
    "Src/stm32f1xx_hal_adc_ex.c",
    "Src/stm32f1xx_hal_spi_ex.c",
    "Src/stm32f1xx_hal_pcd_ex.c",
    "Src/stm32f1xx_hal_i2c.c",
    "Src/stm32f1xx_hal_gpio_ex.c",
    "Src/stm32f1xx_hal_sd.c",
    "Src/stm32f1xx_hal_cec.c",
    "Src/stm32f1xx_hal_usart.c",
    "Src/stm32f1xx_hal_nor.c",
    "Src/stm32f1xx_hal_sram.c",
]
lib = []

stm32_hal_driver = env.StaticLibrary(target=dst, source=src, LIBS=lib, CPPPATH=inc)
Return("stm32_hal_driver")
